package teaproject.UI;

import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import teaproject.Patterns.NotificationDecorator.Notification;
import teaproject.StateMachine.TeapotState;
import teaproject.StateMachine.TeapotStates;

/**
 *
 * @author esena
 */
public class TeaMakerUI extends javax.swing.JFrame {
    private TeaController controller;

    /**
     * Creates new form TeaMakerUI
     */
    public TeaMakerUI() {
        initComponents();

        customInitialization();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_Filled = new javax.swing.JButton();
        jButton_Empty = new javax.swing.JButton();
        jTextField_Count = new javax.swing.JTextField();
        jButton_Reset = new javax.swing.JButton();
        jButton_BoilWaterButton = new javax.swing.JButton();
        jButton_TotalCupsButton = new javax.swing.JButton();
        jLabel_TotalCupCount = new javax.swing.JLabel();
        jPanelState = new javax.swing.JPanel();
        jTextField_Idle = new javax.swing.JTextField();
        jTextField_MakingTea = new javax.swing.JTextField();
        jTextField_BoilingWater = new javax.swing.JTextField();
        jTextField_Done = new javax.swing.JTextField();
        jPanel_Messages = new javax.swing.JPanel();
        jLabel_Messages = new javax.swing.JLabel();
        jTextField_Day = new javax.swing.JTextField();
        jTextField_Date = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton_Filled.setText("FILLED");
        jButton_Filled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FilledActionPerformed(evt);
            }
        });

        jButton_Empty.setText("START");

        jTextField_Count.setText("count");

        jButton_Reset.setText("Reset");
        jButton_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ResetActionPerformed(evt);
            }
        });

        jButton_BoilWaterButton.setText("BOIL WATER");

        jButton_TotalCupsButton.setText("Total Cups");

        jLabel_TotalCupCount.setText("totalCupCount");

        jPanelState.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField_Idle.setEditable(false);
        jTextField_Idle.setText("IDLE");

        jTextField_MakingTea.setEditable(false);
        jTextField_MakingTea.setText("MAKING TEA");

        jTextField_BoilingWater.setEditable(false);
        jTextField_BoilingWater.setText("BOILING WATER");

        jTextField_Done.setEditable(false);
        jTextField_Done.setText("DONE");

        javax.swing.GroupLayout jPanelStateLayout = new javax.swing.GroupLayout(jPanelState);
        jPanelState.setLayout(jPanelStateLayout);
        jPanelStateLayout.setHorizontalGroup(
                jPanelStateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_MakingTea)
                        .addComponent(jTextField_Idle, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField_BoilingWater, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStateLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextField_Done)
                                .addContainerGap())
        );
        jPanelStateLayout.setVerticalGroup(
                jPanelStateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelStateLayout.createSequentialGroup()
                                .addComponent(jTextField_Idle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jTextField_MakingTea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_BoilingWater, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Done, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_Messages.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_Messages.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel_Messages.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jLabel_Messages.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Messages.setText("Messages/Warnings/Notifications");

        javax.swing.GroupLayout jPanel_MessagesLayout = new javax.swing.GroupLayout(jPanel_Messages);
        jPanel_Messages.setLayout(jPanel_MessagesLayout);
        jPanel_MessagesLayout.setHorizontalGroup(
                jPanel_MessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_MessagesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel_Messages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel_MessagesLayout.setVerticalGroup(
                jPanel_MessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_MessagesLayout.createSequentialGroup()
                                .addComponent(jLabel_Messages, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTextField_Day.setText("Day");

        jTextField_Date.setText("Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_Filled)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Count))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jPanel_Messages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jButton_Reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addContainerGap())
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jTextField_Day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextField_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(36, 36, 36))
                                        .addComponent(jButton_BoilWaterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton_TotalCupsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel_TotalCupCount)
                                                .addGap(24, 24, 24))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_Empty, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton_Filled, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_Count))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanelState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton_Empty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton_TotalCupsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_TotalCupCount, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_BoilWaterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jPanel_Messages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField_Day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addComponent(jButton_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ResetActionPerformed
        controller.handleResetButton();
    }//GEN-LAST:event_jButton_ResetActionPerformed

    private void jButton_FilledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FilledActionPerformed
        try {
            int cups = Integer.parseInt(jTextField_Count.getText());
            if (cups > 0) {
                controller.handleFilledButton(cups);
            } else {
                setWrappedText("Please enter a positive number of cups");
            }
        } catch (NumberFormatException e) {
            setWrappedText("Please enter a valid number");
        }    }//GEN-LAST:event_jButton_FilledActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeaMakerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeaMakerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeaMakerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeaMakerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeaMakerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_BoilWaterButton;
    private javax.swing.JButton jButton_Empty;
    private javax.swing.JButton jButton_Filled;
    private javax.swing.JButton jButton_Reset;
    private javax.swing.JButton jButton_TotalCupsButton;
    private javax.swing.JLabel jLabel_Messages;
    private javax.swing.JLabel jLabel_TotalCupCount;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelState;
    private javax.swing.JPanel jPanel_Messages;
    private javax.swing.JTextField jTextField_BoilingWater;
    private javax.swing.JTextField jTextField_Count;
    private javax.swing.JTextField jTextField_Date;
    private javax.swing.JTextField jTextField_Day;
    private javax.swing.JTextField jTextField_Done;
    private javax.swing.JTextField jTextField_Idle;
    private javax.swing.JTextField jTextField_MakingTea;

    public void TakeNotification(Notification notification) {
        setWrappedText(notification.getFormattedMessage());
        TeapotStates state = ((TeapotState) notification.getState()).getStateEnum();
        setStateDisplayHighlight(state);
        
        UpdateActionButtons(state);
    }
    private void UpdateActionButtons(TeapotStates state) {
        if(state == TeapotStates.TEA || state == TeapotStates.BOILING_WATER) {
            disableActionButtons();
        } else if(state == TeapotStates.DONE) {
            enableActionButtons();
        } else {
            enableActionButtons();
        }
    }

    private void setWrappedText(String text) {
        if (text == null || text.isEmpty()) {
            jLabel_Messages.setText("");
            return;
        }
        int baseFontSize = 12;
        int maxCharsPerLine = 45; // Approximate characters per line at base font size
        int estimatedLines = (text.length() + maxCharsPerLine - 1) / maxCharsPerLine;
        
        int fontSize = baseFontSize;
        if (estimatedLines > 2) {
            fontSize = Math.max(9, baseFontSize - (estimatedLines - 2));
        }
        
        String escapedText = text.replace("&", "&amp;")
                                  .replace("<", "&lt;")
                                  .replace(">", "&gt;");
        
        String htmlText = String.format(
            "<html><body style='width: 100%%; font-size: %dpx; text-align: right; padding-right: 5px;'>%s</body></html>",
            fontSize, escapedText
        );
        
        jLabel_Messages.setText(htmlText);
    }


    private static final Color ACTIVE = Color.YELLOW;
    private static final Color INACTIVE = Color.WHITE;

    private void setStateDisplayHighlight(TeapotStates type) {
        resetAllStateFields();

        switch (type) {
            case IDLE:
                jTextField_Idle.setBackground(ACTIVE);
                break;
            case TEA:
                jTextField_MakingTea.setBackground(ACTIVE);
                break;
            case BOILING_WATER:
                jTextField_BoilingWater.setBackground(ACTIVE);
                break;
            case DONE:
                jTextField_Done.setBackground(ACTIVE);
                break;
            case EMPTY:
            default:
                // maybe no highlight or a default
                break;
        }
    }
    
    public void setButtonsEnabled(boolean filled, boolean start, boolean boilWater) {
        jButton_Filled.setEnabled(filled);
        jButton_Empty.setEnabled(start);
        jButton_BoilWaterButton.setEnabled(boilWater);
    }
    
    public void disableActionButtons() {
        setButtonsEnabled(false, false, false);
    }
    
    public void enableActionButtons() {
        setButtonsEnabled(true, true, true);
    }


    private void resetAllStateFields() {
        jTextField_Idle.setBackground(INACTIVE);
        jTextField_MakingTea.setBackground(INACTIVE);
        jTextField_BoilingWater.setBackground(INACTIVE);
        jTextField_Done.setBackground(INACTIVE);
    }

    private void customInitialization(){
        updateDateTime();
        jButton_Empty.addActionListener(evt -> jButton_StartActionPerformed(evt));
        jButton_BoilWaterButton.addActionListener(evt -> jButton_BoilWaterActionPerformed(evt));
        jButton_TotalCupsButton.addActionListener(evt -> jButton_TotalCupsActionPerformed(evt));
        controller = new TeaController(this);
    }


    private void jButton_StartActionPerformed(java.awt.event.ActionEvent evt) {
        controller.handleStartButton();
    }

    private void jButton_BoilWaterActionPerformed(java.awt.event.ActionEvent evt) {
        controller.handleBoilWaterButton();
    }
    private void jButton_TotalCupsActionPerformed(java.awt.event.ActionEvent evt) {
        int total = controller.getTodayCups();
        jLabel_TotalCupCount.setText(String.valueOf(total));
    }


    // End of variables declaration//GEN-END:variables

    private void updateDateTime() {
        java.time.LocalDateTime now = java.time.LocalDateTime.now();
        jTextField_Day.setText(now.getDayOfWeek().toString());
        jTextField_Date.setText(now.format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd")));
    }
}
